#ifndef GBA_MEMORY_H
#define GBA_MEMORY_H


#define DEVICE_BASE(n) ((void*)(0x1000000 * (n)))

#define KILOBYTES(k) (1024 * (k))
#define MEGABYTES(m) (1024 * KILOBYTES(k))

#define EWRAM_BASE DEVICE_BASE(2)
#define EWRAM_SIZE KILOBYTES(256)

#define IWRAM_BASE DEVICE_BASE(3)
#define IWRAM_SIZE KILOBYTES(32)

#define REG_BASE DEVICE_BASE(4)

#define PALRAM_BASE DEVICE_BASE(5)
#define COLORS_PER_ROW (16)
#define PALETTE_ROW_SIZE (COLORS_PER_ROW * 2)
#define ROWS_PER_PALETTE (16)
#define COLORS_PER_PALETTE (COLORS_PER_ROW * ROWS_PER_PALETTE)
#define PALETTE_SIZE (COLORS_PER_PALETTE * 2)
#define BG_PALETTE PALRAM_BASE
#define OBJ_PALETTE (PALRAM_BASE + PALETTE_SIZE)
#define PALRAM_SIZE (PALETTE_SIZE * 2)

#define VRAM_BASE DEVICE_BASE(6)
#define VRAM_SIZE KILOBYTES(96)

#define OAM_BASE DEVICE_BASE(7)
#define OAM_SIZE KILOBYTES(1)

#define ROM_BASE DEVICE_BASE(8)
#define ROM_SIZE MEGABYTES(32)

#define SRAM_BASE DEVICE_BASE(14)
#define SRAM_SIZE KILOBYTES(32)

#endif /* GBA_MEMORY_H */
