#ifndef GBA_PALETTE_H
#define GBA_PALETTE_H


#define COLORS_PER_ROW (16)
#define PALETTE_ROW_SIZE (COLORS_PER_ROW * 2)

#define ROWS_PER_PALETTE (16)
#define COLORS_PER_PALETTE (COLORS_PER_ROW * ROWS_PER_PALETTE)
#define PALETTE_SIZE (PALETTE_ROW_SIZE * ROWS_PER_PALETTE)

#define BG_PALETTE PALRAM_BASE
#define OBJ_PALETTE (PALRAM_BASE + PALETTE_SIZE)


#define PALETTE_ROW(n) (PALETTE_ROW_SIZE * (n))

#endif  // GBA_PALETTE_H