#ifndef CUTSCENE_LAYERED_OAM_ANIM_H
#define CUTSCENE_LAYERED_OAM_ANIM_H

#include "types.h"

extern u8 sLayeredCutsceneOamFrame000;
extern u8 sLayeredCutsceneOamFrame001;
extern u8 sLayeredCutsceneOamFrame002;
extern u8 sLayeredCutsceneOamFrame003;
extern u8 sLayeredCutsceneOamFrame004;
extern u8 sLayeredCutsceneOamFrame005;
extern u8 sLayeredCutsceneOamFrame006;
extern u8 sLayeredCutsceneOamFrame007;
extern u8 sLayeredCutsceneOamFrame008;
extern u8 sLayeredCutsceneOamFrame009;
extern u8 sLayeredCutsceneOamFrame010;
extern u8 sLayeredCutsceneOamFrame011;
extern u8 sLayeredCutsceneOamFrame012;
extern u8 sLayeredCutsceneOamFrame013;
extern u8 sLayeredCutsceneOamFrame014;
extern u8 sLayeredCutsceneOamFrame015;
extern u8 sLayeredCutsceneOamFrame016;
extern u8 sLayeredCutsceneOamFrame017;
extern u8 sLayeredCutsceneOamFrame018;
extern u8 sLayeredCutsceneOamFrame019;
extern u8 sLayeredCutsceneOamFrame020;
extern u8 sLayeredCutsceneOamFrame021;
extern u8 sLayeredCutsceneOamFrame022;
extern u8 sLayeredCutsceneOamFrame023;
extern u8 sLayeredCutsceneOamFrame024;
extern u8 sLayeredCutsceneOamFrame025;
extern u8 sLayeredCutsceneOamFrame026;
extern u8 sLayeredCutsceneOamFrame027;
extern u8 sLayeredCutsceneOamFrame028;
extern u8 sLayeredCutsceneOamFrame029;
extern u8 sLayeredCutsceneOamFrame030;
extern u8 sLayeredCutsceneOamFrame031;
extern u8 sLayeredCutsceneOamFrame032;
extern u8 sLayeredCutsceneOamFrame033;
extern u8 sLayeredCutsceneOamFrame034;
extern u8 sLayeredCutsceneOamFrame035;
extern u8 sLayeredCutsceneOamFrame036;
extern u8 sLayeredCutsceneOamFrame037;
extern u8 sLayeredCutsceneOamFrame038;
extern u8 sLayeredCutsceneOamFrame039;
extern u8 sLayeredCutsceneOamFrame040;
extern u8 sLayeredCutsceneOamFrame041;
extern u8 sLayeredCutsceneOamFrame042;
extern u8 sLayeredCutsceneOamFrame043;
extern u8 sLayeredCutsceneOamFrame044;
extern u8 sLayeredCutsceneOamFrame045;
extern u8 sLayeredCutsceneOamFrame046;
extern u8 sLayeredCutsceneOamFrame047;
extern u8 sLayeredCutsceneOamFrame048;
extern u8 sLayeredCutsceneOamFrame049;
extern u8 sLayeredCutsceneOamFrame050;
extern u8 sLayeredCutsceneOamFrame051;
extern u8 sLayeredCutsceneOamFrame052;
extern u8 sLayeredCutsceneOamFrame053;
extern u8 sLayeredCutsceneOamFrame054;
extern u8 sLayeredCutsceneOamFrame055;
extern u8 sLayeredCutsceneOamFrame056;
extern u8 sLayeredCutsceneOamFrame057;
extern u8 sLayeredCutsceneOamFrame058;
extern u8 sLayeredCutsceneOamFrame059;
extern u8 sLayeredCutsceneOamFrame060;
extern u8 sLayeredCutsceneOamFrame061;
extern u8 sLayeredCutsceneOamFrame062;
extern u8 sLayeredCutsceneOamFrame063;
extern u8 sLayeredCutsceneOamFrame064;
extern u8 sLayeredCutsceneOamFrame065;
extern u8 sLayeredCutsceneOamFrame066;
extern u8 sLayeredCutsceneOamFrame067;
extern u8 sLayeredCutsceneOamFrame068;
extern u8 sLayeredCutsceneOamFrame069;
extern u8 sLayeredCutsceneOamFrame070;
extern u8 sLayeredCutsceneOamFrame071;
extern u8 sLayeredCutsceneOamFrame072;
extern u8 sLayeredCutsceneOamFrame073;
extern u8 sLayeredCutsceneOamFrame074;
extern u8 sLayeredCutsceneOamFrame075;
extern u8 sLayeredCutsceneOamFrame076;
extern u8 sLayeredCutsceneOamFrame077;
extern u8 sLayeredCutsceneOamFrame078;
extern u8 sLayeredCutsceneOamFrame079;
extern u8 sLayeredCutsceneOamFrame080;
extern u8 sLayeredCutsceneOamFrame081;
extern u8 sLayeredCutsceneOamFrame082;
extern u8 sLayeredCutsceneOamFrame083;
extern u8 sLayeredCutsceneOamFrame084;
extern u8 sLayeredCutsceneOamFrame085;
extern u8 sLayeredCutsceneOamFrame086;
extern u8 sLayeredCutsceneOamFrame087;
extern u8 sLayeredCutsceneOamFrame088;
extern u8 sLayeredCutsceneOamFrame089;
extern u8 sLayeredCutsceneOamFrame090;
extern u8 sLayeredCutsceneOamFrame091;
extern u8 sLayeredCutsceneOamFrame092;
extern u8 sLayeredCutsceneOamFrame093;
extern u8 sLayeredCutsceneOamFrame094;

s32 SelectLayeredCutsceneOamSequence00(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence01(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence02(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence03(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence04(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence05(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence06(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence07(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence08(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence09(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence10(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence11(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence12(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence13(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence14(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence15(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence16(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence17(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence18(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence19(s32 timer, u8 **oamFrame);
s32 SelectLayeredCutsceneOamSequence20(s32 timer, u8 **oamFrame);
void SelectLayeredCutsceneOamSequence21(s32 timer, u8 **oamFrame);
void SelectLayeredCutsceneOamSequence22(s32 timer, u8 **oamFrame);
void SelectLayeredCutsceneOamSequence23(s32 timer, u8 **oamFrame);
void SelectLayeredCutsceneOamSequence24(s32 timer, u8 **oamFrame);

#endif // CUTSCENE_LAYERED_OAM_ANIM_H
