#ifndef SOUND_H
#define SOUND_H

#include "gba.h"


enum SoundID {
    SOUND_36 = 0x36,
    SOUND_37,
    SOUND_38,
    SOUND_39,
    SOUND_3A,
    SOUND_3B,
    SOUND_3C,
    SOUND_3D,

    SE_BOX_OPEN = 0xDC,

    SE_THUNDER = 0x115,

    SE_CONFIRM = 0x125,

    SE_GET_COIN_10POINTS = 0x136,
    SE_GET_COIN_50POINTS,
    SE_GET_COIN_100POINTS,
    SE_GET_COIN_500POINTS,
    SE_GET_DIAMOND,
    SE_GET_JEWEL_PIECE,
    SE_GET_CD,
    SOUND_13D,
    SOUND_13E,
    SOUND_13F,
    SE_GET_HEART,
    SOUND_141,
    SOUND_142,
    SE_GET_HEALTH_REFILL,
    SE_GET_LITTLE_HEART,

    SE_GET_COIN_10POINTS_UNDERWATER = 0x14B,
    SE_GET_COIN_50POINTS_UNDERWATER,
    SE_GET_COIN_100POINTS_UNDERWATER,
    SE_GET_COIN_500POINTS_UNDERWATER,
    SE_GET_DIAMOND_UNDERWATER,

    SE_GET_LITTLE_HEART_UNDERWATER = 0x155,
    SE_GET_ALL_JEWEL_PIECES,

    SE_RESULTS_FOUND_CD = 0x1D0,

    SE_GET_MINIGAME_MEDAL = 0x223,

    SE_HIGH_SCORE = 0x252,
};


void Sound_Init(void);
void func_80022C8(u32);
void Sound_Play(u16);

#endif  // SOUND_H
